-- ============================================================
-- Slug & Dandelion — 2026-08 SPORTS
-- Clean schema, no auth/passwords required this month.
-- Run in the Supabase SQL editor on a fresh project.
-- ============================================================

-- ── RSVPs ────────────────────────────────────────────────────────────────────

create table if not exists public.sports_rsvps (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  name          text        not null check (char_length(name) <= 80),
  guests        int         not null default 0 check (guests >= 0),
  phone         text                 check (phone is null or char_length(phone) <= 30),
  email         text                 check (email is null or char_length(email) <= 120),
  message       text                 check (message is null or char_length(message) <= 280),
  crowd_message text                 check (crowd_message is null or char_length(crowd_message) <= 32),
  section       text        not null default 'L' check (section ~ '^(L|M|R)$'),
  box           text        not null default 'A' check (box ~ '^[A-D]$'),
  seat          text        not null default '1' check (seat ~ '^[1-4]$'),
  jersey_number text        not null default '00' check (jersey_number ~ '^[0-9]{1,2}$')
);

alter table public.sports_rsvps
  add column if not exists crowd_message text check (crowd_message is null or char_length(crowd_message) <= 32);

create unique index if not exists sports_rsvps_unique_seat
on public.sports_rsvps (section, box, seat)
where section ~ '^(L|M|R)$' and box ~ '^[A-D]$' and seat ~ '^[1-4]$';

alter table public.sports_rsvps enable row level security;

grant select, insert, update on public.sports_rsvps to anon, authenticated;
grant usage, select on sequence public.sports_rsvps_id_seq to anon, authenticated;

drop policy if exists "Public read sports rsvps" on public.sports_rsvps;
create policy "Public read sports rsvps"
on public.sports_rsvps for select
to anon, authenticated
using (true);

drop policy if exists "Public insert sports rsvps" on public.sports_rsvps;
create policy "Public insert sports rsvps"
on public.sports_rsvps for insert
to anon, authenticated
with check (true);

drop policy if exists "Public update sports rsvps" on public.sports_rsvps;
create policy "Public update sports rsvps"
on public.sports_rsvps for update
to anon, authenticated
using (true)
with check (true);

-- ── Toasters / poppers click counter ────────────────────────────────────────

create table if not exists public.toasters_poppers_click_counter (
  id              int primary key check (id = 1),
  toasters_clicks bigint      not null default 0,
  poppers_clicks  bigint      not null default 0,
  updated_at      timestamptz not null default now()
);

insert into public.toasters_poppers_click_counter (id, toasters_clicks, poppers_clicks)
values (1, 0, 0)
on conflict (id) do nothing;

alter table public.toasters_poppers_click_counter enable row level security;
revoke all on public.toasters_poppers_click_counter from public, anon, authenticated;

create or replace function public.increment_toasters_poppers_clicks(p_team text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_team text := upper(trim(coalesce(p_team, '')));
  next_toasters bigint;
  next_poppers bigint;
begin
  if normalized_team not in ('TOASTERS', 'POPPERS') then
    raise exception 'Invalid team. Expected TOASTERS or POPPERS.' using errcode = '22023';
  end if;

  update public.toasters_poppers_click_counter
  set toasters_clicks = toasters_clicks + case when normalized_team = 'TOASTERS' then 1 else 0 end,
      poppers_clicks = poppers_clicks + case when normalized_team = 'POPPERS' then 1 else 0 end,
      updated_at = now()
  where id = 1
  returning toasters_clicks, poppers_clicks into next_toasters, next_poppers;

  return jsonb_build_object(
    'toasters_clicks', coalesce(next_toasters, 0),
    'poppers_clicks', coalesce(next_poppers, 0),
    'total_clicks', coalesce(next_toasters, 0) + coalesce(next_poppers, 0)
  );
end;
$$;

create or replace function public.get_toasters_poppers_click_counter()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'toasters_clicks', coalesce(toasters_clicks, 0),
    'poppers_clicks', coalesce(poppers_clicks, 0),
    'total_clicks', coalesce(toasters_clicks, 0) + coalesce(poppers_clicks, 0)
  )
  from public.toasters_poppers_click_counter
  where id = 1;
$$;

revoke all on function public.increment_toasters_poppers_clicks(text) from public;
grant execute on function public.increment_toasters_poppers_clicks(text) to anon, authenticated;
revoke all on function public.get_toasters_poppers_click_counter() from public;
grant execute on function public.get_toasters_poppers_click_counter() to anon, authenticated;

-- ── Site visitor counter (unique by local visitor id) ───────────────────────

create table if not exists public.site_counter (
  id           bigint generated by default as identity primary key,
  visitor_id   text        not null unique check (char_length(visitor_id) between 8 and 64),
  first_seen   timestamptz not null default now(),
  last_seen    timestamptz not null default now(),
  visit_count  int         not null default 1 check (visit_count >= 1)
);

alter table public.site_counter enable row level security;
revoke all on public.site_counter from public, anon, authenticated;

create or replace function public.register_site_visitor(p_visitor_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_id text := trim(coalesce(p_visitor_id, ''));
  is_new_visitor boolean := false;
  unique_visitors bigint := 0;
begin
  if normalized_id = '' then
    raise exception 'visitor_id is required.' using errcode = '22023';
  end if;

  insert into public.site_counter (visitor_id)
  values (normalized_id)
  on conflict (visitor_id) do nothing;

  is_new_visitor := found;

  if not is_new_visitor then
    update public.site_counter
    set last_seen = now(),
        visit_count = visit_count + 1
    where visitor_id = normalized_id;
  end if;

  select count(*) into unique_visitors from public.site_counter;

  return jsonb_build_object(
    'is_new_visitor', is_new_visitor,
    'unique_visitors', coalesce(unique_visitors, 0)
  );
end;
$$;

create or replace function public.get_site_counter()
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint from public.site_counter;
$$;

revoke all on function public.register_site_visitor(text) from public;
grant execute on function public.register_site_visitor(text) to anon, authenticated;
revoke all on function public.get_site_counter() from public;
grant execute on function public.get_site_counter() to anon, authenticated;
