-- ============================================================
-- Slug & Dandelion — 2026-08 SPORTS
-- Clean schema, no auth/passwords required this month.
-- Run in the Supabase SQL editor on a fresh project.
-- ============================================================

-- ── RSVPs ────────────────────────────────────────────────────────────────────

create table if not exists public.sports_rsvps (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  name          text        not null check (char_length(name) <= 80),
  guests        int         not null default 0 check (guests >= 0),
  phone         text                 check (phone is null or char_length(phone) <= 30),
  email         text                 check (email is null or char_length(email) <= 120),
  message       text                 check (message is null or char_length(message) <= 280),
  crowd_message text                 check (crowd_message is null or char_length(crowd_message) <= 32),
  section       text        not null default 'L' check (section ~ '^(L|M|R)$'),
  box           text        not null default 'A' check (box ~ '^[A-D]$'),
  seat          text        not null default '1' check (seat ~ '^[1-4]$'),
  jersey_number text        not null default '00' check (jersey_number ~ '^[0-9]{1,2}$')
);

alter table public.sports_rsvps
  add column if not exists crowd_message text check (crowd_message is null or char_length(crowd_message) <= 32);

create unique index if not exists sports_rsvps_unique_seat
on public.sports_rsvps (section, box, seat)
where section ~ '^(L|M|R)$' and box ~ '^[A-D]$' and seat ~ '^[1-4]$';

alter table public.sports_rsvps enable row level security;

grant select, insert, update on public.sports_rsvps to anon, authenticated;
grant usage, select on sequence public.sports_rsvps_id_seq to anon, authenticated;

drop policy if exists "Public read sports rsvps" on public.sports_rsvps;
create policy "Public read sports rsvps"
on public.sports_rsvps for select
to anon, authenticated
using (true);

drop policy if exists "Public insert sports rsvps" on public.sports_rsvps;
create policy "Public insert sports rsvps"
on public.sports_rsvps for insert
to anon, authenticated
with check (true);

drop policy if exists "Public update sports rsvps" on public.sports_rsvps;
create policy "Public update sports rsvps"
on public.sports_rsvps for update
to anon, authenticated
using (true)
with check (true);

-- ── Site counter ─────────────────────────────────────────────────────────────

create table if not exists public.site_counter (
  id            int primary key check (id = 1),
  visitor_count bigint      not null default 0,
  updated_at    timestamptz not null default now()
);

insert into public.site_counter (id, visitor_count)
values (1, 0)
on conflict (id) do nothing;

alter table public.site_counter enable row level security;
revoke all on public.site_counter from public, anon, authenticated;

create or replace function public.increment_site_counter()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  update public.site_counter
  set visitor_count = visitor_count + 1,
      updated_at    = now()
  where id = 1
  returning visitor_count into new_count;
  return coalesce(new_count, 0);
end;
$$;

create or replace function public.get_site_counter()
returns bigint
language sql
security definer
set search_path = public
as $$
  select coalesce(visitor_count, 0) from public.site_counter where id = 1;
$$;

revoke all on function public.increment_site_counter() from public;
grant execute on function public.increment_site_counter() to anon, authenticated;
revoke all on function public.get_site_counter() from public;
grant execute on function public.get_site_counter() to anon, authenticated;
